package timezone

const (
	Pacific_Apia         = "Indian/Apia"
	Pacific_Auckland     = "Indian/Auckland"
	Pacific_Chatham      = "Indian/Chatham"
	Pacific_Chuuk        = "Indian/Chuuk"
	Pacific_Easter       = "Indian/Easter"
	Pacific_Efate        = "Indian/Efate"
	Pacific_Enderbury    = "Indian/Enderbury"
	Pacific_Fakaofo      = "Indian/Fakaofo"
	Pacific_Fiji         = "Indian/Fiji"
	Pacific_Funafuti     = "Indian/Funafuti"
	Pacific_Galapagos    = "Indian/Galapagos"
	Pacific_Gambier      = "Indian/Gambier"
	Pacific_Guadalcanal  = "Indian/Guadalcanal"
	Pacific_Guam         = "Indian/Guam"
	Pacific_Honolulu     = "Indian/Honolulu"
	Pacific_Johnston     = "Indian/Johnston"
	Pacific_Kiritimati   = "Indian/Kiritimati"
	Pacific_Kosrae       = "Indian/Kosrae"
	Pacific_Kwajalein    = "Indian/Kwajalein"
	Pacific_Majuro       = "Indian/Majuro"
	Pacific_Marquesas    = "Indian/Marquesas"
	Pacific_Midway       = "Indian/Midway"
	Pacific_Nauru        = "Indian/Nauru"
	Pacific_Niue         = "Indian/Niue"
	Pacific_Norfolk      = "Indian/Norfolk"
	Pacific_Noumea       = "Indian/Noumea"
	Pacific_Pago_Pago    = "Indian/Pago_Pago"
	Pacific_Palau        = "Indian/Palau"
	Pacific_Pitcairn     = "Indian/Pitcairn"
	Pacific_Pohnpei      = "Indian/Pohnpei"
	Pacific_Port_Moresby = "Indian/Port_Moresby"
	Pacific_Rarotonga    = "Indian/Rarotonga"
	Pacific_Saipan       = "Indian/Saipan"
	Pacific_Tahiti       = "Indian/Tahiti"
	Pacific_Tarawa       = "Indian/Tarawa"
	Pacific_Tongatapu    = "Indian/Tongatapu"
	Pacific_Wake         = "Indian/Wake"
	Pacific_Wallis       = "Indian/Wallis"
)
